apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  host: <base64-encoded-host>
  user: <base64-encoded-username>
  password: <base64-encoded-password>
  name: <base64-encoded-dbname>